### PR TITLE
Add DrawingUtil static functions

### LINKED ISSUE #1: Code utility functions to draw 2D shapes easily in Godot
Code a set of functions to draw helpers, gizmos, and visualize what's happening
in the editor. It's for teaching purposes and visualization, so we can start to
show what's happening in our tuts a bit more. So I would like these to be
accessible from code, not as a node.

See this for a starting point: https://github.com/GDQuest/godot-platformer-2d/blob/master/game/src/Autoload/DrawingUtils.gd
You can start from it.

All functions should support an optional stroke: drawing first a larger
background shape, then a smaller one inside.

Shapes:

- Vectors: draw a line with an arrow.
- A 2D Arc.
- Ellipses.
- Grid lines: Orthogonal and isometric. That's to draw the lines of tilemaps. This should draw based on simple parameters like the grid's size in cells and the size of one cell. That kind of information is available on TileMap nodes.
- Grid cells: Othogonal and isometric. To highlight one cell on the grid, e.g. the position of the character, a cell an AI is looking at.

### PR DESCRIPTION
**Pull request by henriiquecampos**
Close #1

### CODE REVIEW

**Comment by NathanLovato** [comment]
@razcore-art @Razoric480 may I ask you to check out this one? These are functions to draw for debugging purposes. I think I suggested to go with static functions, but now I'm not sure a type that extends canvasitem wouldn't simplify usage.

Because then you could set it as toplevel and draw anything in global space, if you only wanted one canvas, or have instances that draw locally.

What do you think?

**Comment by NathanLovato** [comment]
I'm working on it right now, refactoring and testing some changes.
Regarding the outline, I'd use an Outline object for drawing, to avoid having the flag and extra parameters. I wonder if inner classes or simple classes wouldn't simplify the code in general. For outline I'm pretty sure it makes things easier to change later, as you merge 3 parameters into one:

```gdscript
func draw_*(
...
			use_outline := false,
			outline_width := 4.0,
			outline_color := Color.white,
```

vs

```gdscript
func draw_*(
...
			outline: ShapeOutline = null
```

Otherwise, right now, we get functions with up to 10+ parameters, calls like these get hard to refactor.

**Comment by NathanLovato** [comment]
We have some other options, API-wise, that are more object-oriented and convenient for the user, but I'd like your thoughts on that:

1. Having a single draw_shape public function that maps the shape to the drawing call. I think it's not too extensible, and not the best performance-wise, but it gives nice code to the user:

```gdscript
var triangle := Triangle.new(center, radius, ...)
draw_shape(triangle)
```

Internally, draw_shape would map the shape to the corresponding drawing function:

```gdscript
func draw_shape(shape: Shape) -> void:
    if shape is Triangle:
        draw_triangle(shape)
...
```

2. Having one class for each shape to draw, with the properties and drawing code. + some basic data container classes to encapsulate generic drawing parameters (color, outline, angle, scale...).

The issue I see with the current code is that it's going to be hard to change anything later on. I'm not sure how to best make this both easy to maintain and to use.

**Comment by Razoric480** [comment]
On the one hand, having static functions in a single utility makes it easy to call from anywhere if you just need a quick visualization.

On the other, having it as a canvas item means you can extend it via a Spatial or Node2D script and just call whatever you need from it from _draw. And it saves a parameter by not needing to pass in a canvas_item object.

**Comment by Razoric480** [comment]
As for single use functions VS creating shapes, I think if the goal is to improve on godot's draw_ functions, going with OOP would be a pretty intuitive way to go about it.

Open closed principle says that a class should be open to extension, but closed to modification. If we want to add a new shape down the line, we can create a new class without having to modify the Utils script.

**Comment by NathanLovato** [comment]
> On the one hand, having static functions in a single utility makes it easy to call from anywhere if you just need a quick visualization.

Yes, that's what I was thinking, and why I suggested going that route initially. But if you start having function calls like these, they're a pain to change later on:

```gdscript
draw_arc(canvas_item, center, radius, angle_start, angle_end, point_count, color, width, use_outline, outline_width, outline_color)
```

You can simplify it like so at least:

```gdscript
draw_arc(canvas_item, arc, drawing_parameters)
```

`drawing_parameters` containing the outline maybe? Or

```gdscript
draw_arc(canvas_item, arc, drawing_params, outline)
```

**Comment by NathanLovato** [comment]
Yes I guess it makes sense to try and stay consistent with how Godot does it, using a node.

**Comment by NathanLovato** [comment]
Here's a first pass refactoring the code. I rewrote the ellipse draw function to not rely on 3D mesh resources. Long lines and function parameters are now wrapped, one per line. Two tabs for hanging indents.

Speaking of which, how about we only use 1 extra tab for hanging indents? I don't know why they went for 2 in the official styleguide, 1 reads well already. On GitHub diffs, tabs are also huge, having an extra two pushes all the text to the right.

**Comment by Razoric480** [comment]
I'd prefer 1 as well. Not sure why 2 - I guess the principle behind it is to differentiate between a "wrapped set of parameters" and a scoped block for if statements, functions and loops.

**Comment by henriiquecampos** [comment]
Looking good to me, some nice improvements. The line skipped arguments look way better, didn't think of that :sweat_smile: 

Is it good to merge?

**Comment by NathanLovato** [comment]
I'll merge and open an issue to rethink the design. But I need to use them as part of a project for that. for the next course/tuts, we should start adding some visualization.

Or @Razoric480 should/could we use this as a base for debug visualization in the steering framework?

**Comment by Razoric480** [comment]
There _is_ an open issue about visualization on the framework, so could be an opportunity to try it out that way.

**Pull request merged**
